seed: 1234
dataset: "paths"
logdir: "model"
Tmax: 0.25

encoder:
  input: "rgb+"
  arch: "CNNDownSize"
  depth: 4
  const: 10.0

params:
  batch_size: 100
  num_epochs: 100
  lr: 0.0001


hydra:
  job:
    chdir: False
